Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,33 +1,40 @@
-name: Sync Fork with Upstream
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
   schedule:
-    - cron: '6 9 * * *'  # Runs daily at midnight (adjust as needed)
-  workflow_dispatch:  # Manually trigger the workflow
+    - cron: "0 0 * * *" # every day
+  workflow_dispatch:
 
 jobs:
-  sync:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
     steps:
-    - name: Checkout Fork
-      uses: actions/checkout@v2
-      with:
-        ref: V2  # Make sure you're on the V2 branch
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
 
-    - name: Set Up Git
-      run: |
-        git config --global user.name "GitHub Actions"
-        git config --global user.email "actions@github.com"
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo:  xishang0128/sparkle
+          upstream_sync_branch: master
+          target_sync_branch: master
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-    - name: Add Upstream Remote
-      run: git remote add upstream https://github.com/xishang0128/sparkle.git
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
 
-    - name: Fetch Upstream
-      run: git fetch upstream
-
-    - name: Merge Upstream into V2 Branch
-      run: |
-        git checkout V2  # Switch to your V2 branch
-        git merge upstream/master  # Merge from upstream's master branch
-        git push origin V2  # Push the changes to your fork
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
